In [2]:
import pandas as pd

In [3]:
coffee = pd.read_csv('coffee.csv')

In [4]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending = [False,True])
coffee.head(7)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40

In [5]:
oly = pd.read_excel('olympics-data.xlsx')
oly.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [5]:
oly.to_parquet()
print(end='')

In [6]:
display(oly.loc[0:4,['name','born_city']])
oly.iloc[3,3] = 'SHiva'
oly.iloc[0:4,[1,3]]   #Upper index is not inclusive

                    name    born_city
0  Jean-François Blanchy     Bordeaux
1         Arnaud Boetsch       Meulan
2           Jean Borotra     Biarritz
3        Jacques Brugnon  Paris VIIIe
4           Albert Canet   Wandsworth

                    name born_city
0  Jean-François Blanchy  Bordeaux
1         Arnaud Boetsch    Meulan
2           Jean Borotra  Biarritz
3        Jacques Brugnon     SHiva

In [7]:
oly.loc[oly['height_cm']>220,['name','born_city']]
oly[(oly['height_cm']>220) & (oly['born_city']=='Crossnore')][['name','born_city']]

                name  born_city
5781  Tommy Burleson  Crossnore

In [25]:
display(oly['name'].str.contains('Shiva | Teja',case=False))
oly[oly['name'].str.contains('Shiva | Teja',case=False)]

0         False
1         False
2         False
3         False
4         False
          ...
145495    False
145496    False
145497    False
145498    False
145499    False
Name: name, Length: 145500, dtype: bool

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1525,1532,Félix Tejada,1976-05-02,NaN,NaN,NaN,Dominican Republic,NaN,NaN,NaN
99707,100506,Shiva Keshavan,1981-08-25,Delhi,National Capital Territory of Delhi,IND,Independent Olympic Athletes India,183.0,85.0,NaN
120557,122482,Shiva Thapa,1993-12-08,Guwahati,Assam,IND,India,169.0,56.0,NaN

In [6]:
oly.query('(born_country == "IND") & (born_region == "Andhra Pradesh")')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
281,282,S. M. Hadi,1899-08-12,Hyderabad,Andhra Pradesh,IND,India,NaN,NaN,1971-07-14
3858,3871,Robert Cranston,1928-10-30,Gooty,Andhra Pradesh,IND,India,NaN,NaN,2014-06-09
19014,19147,Joe Antic,1931-03-13,Secunderabad,Andhra Pradesh,IND,India,168.0,59.0,2016-07-12
19085,19219,Mukesh Kumar Nandanoori,1970-04-16,Hyderabad,Andhra Pradesh,IND,India,175.0,64.0,NaN
25606,25798,Sayed Khwaja Aziz-ud-Din,1930-07-12,Gocha Mahal,Andhra Pradesh,IND,India,NaN,NaN,1998-01-01
25607,25799,Tulasidas Balaram,1936-11-30,Secunderabad,Andhra Pradesh,IND,India,171.0,56.0,2023-02-16
25617,25809,Dharmalingam Kannan,1936-07-08,Secunderabad,Andhra Pradesh,IND,India,163.0,54.0,2006-05-19
25620,25812,Youssef Khan,1937-08-05,Hyderabad,Andhra Pradesh,IND,India,172.0,56.0,2006-07-01
25642,25834,Peter Thangaraj,1935-12-24,Hyderabad,Andhra Pradesh,IND,India,190.0,85.0,2008-11-24
46816,47165,Sheila Watt,1941-01-27,Pitapuram,Andhra Pradesh,IND,Great Britain,164.0,64.0,2023-03-10
47928,48280,Shamsher Khan,1931-01-01,Kaithepalle,Andhra Pradesh,IND,India,NaN,NaN,2017-10-15
60816,61255,Ahmed Abdul Basith,1942-01-09,Hyderabad,Andhra Pradesh,IND,India,178.0,75.0,2021-01-01
106400,107497,Sharath Kamal Achanta,1982-07-12,Machilipatnam,Andhra Pradesh,IND,India,186.0,85.0,NaN
107178,108301,Sathi Geetha,1983-07-05,Martur,Andhra Pradesh,IND,India,156.0,52.0,NaN
110298,111512,Pranitha Vardhineni,1990-11-17,Kalleda,Andhra Pradesh,IND,India,155.0,67.0,NaN
116228,117613,Sania Mirza,1986-11-15,Hyderabad,Andhra Pradesh,IND,India,173.0,57.0,NaN
118538,120264,Rushmi Chakravarthi,1977-10-09,Hyderabad,Andhra Pradesh,IND,India,170.0,65.0,NaN
121855,123878,Jagadeesan Vishnuvardhan,1987-07-27,Secunderabad,Andhra Pradesh,IND,India,188.0,84.0,NaN
123480,125680,Parupalli Kashyap,1986-09-08,Hyderabad,Andhra Pradesh,IND,India,173.0,NaN,NaN
128046,130550,P. V. Sindhu,1995-07-05,Hyderabad,Andhra Pradesh,IND,India,179.0,65.0,NaN
131620,134434,B. Sumeeth Reddy,1991-09-26,Gungal,Andhra Pradesh,IND,India,182.0,64.0,NaN
131621,134435,Srikanth Kidambi,1993-02-07,Guntur,Andhra Pradesh,IND,India,178.0,66.0,NaN
131636,134452,Kynan Chenai,1991-01-29,Hyderabad,Andhra Pradesh,IND,India,200.0,85.0,NaN

In [10]:
coffee = coffee.rename(columns={'Coffee Type' : 'Coffee'})
coffee.head()

         Day    Coffee  Units Sold
0     Monday  Espresso          25
1     Monday     Latte          15
2    Tuesday  Espresso          30
3    Tuesday     Latte          20
4  Wednesday  Espresso          35

In [11]:
coffee['taste'] = coffee['Coffee'].apply(lambda x: 'Bad' if x == 'Espresso' else ('Average' if x == 'Latte' else 'Awesome'))

In [12]:
nocs = pd.read_csv('noc_regions.csv')

In [13]:
oly_new = pd.merge(oly,nocs[['NOC','region']],left_on='born_country',right_on='NOC', how='left')

In [14]:
oly_new.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France

In [15]:
results = pd.read_parquet('results.parquet')
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [16]:
combined_df = pd.merge(oly[['name','athlete_id']],results,on='athlete_id')

In [17]:
combined_df.drop(columns = ['athlete_id','noc'],inplace=True)
combined_df.head()

,name,year,type,discipline,event,as,team,place,tied,medal
0,Jean-François Blanchy,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,None,17.0,True,None
1,Jean-François Blanchy,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,Jean Montariol,NaN,False,None
2,Jean-François Blanchy,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,None,32.0,True,None
3,Jean-François Blanchy,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,Jeanne Vaussard,8.0,True,None
4,Jean-François Blanchy,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,Jacques Brugnon,4.0,False,None

In [18]:
coffee.groupby('Coffee')['Units Sold'].sum()

Coffee
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [19]:
coffee.groupby('Coffee').count()

          Day  Units Sold  taste
Coffee
Espresso    7           7      7
Latte       7           7      7

In [20]:
coffee.head()

         Day    Coffee  Units Sold    taste
0     Monday  Espresso          25      Bad
1     Monday     Latte          15  Average
2    Tuesday  Espresso          30      Bad
3    Tuesday     Latte          20  Average
4  Wednesday  Espresso          35      Bad

In [21]:
pivot_coffee = pd.pivot(coffee,values='Units Sold',index = 'Day',columns = 'Coffee').sort_values('Day')
pivot_coffee

Coffee     Espresso  Latte
Day
Friday           45     35
Monday           25     15
Saturday         45     35
Sunday           45     35
Thursday         40     30
Tuesday          30     20
Wednesday        35     25

In [1]:
df = pd.DataFrame({

    'name': ['Alice', 'Bob', 'Charlie']

})
df.insert(1,'Column_name',['A','b','23'])

NameError: name 'df' is not defined

In [ ]:
df['new_column'] = [1,2,3] #Just passsing a list creates a new column